prompt >> Creation of dbschema smartworkplace
DROP USER SMARTWORKPLACE CASCADE;

CREATE USER SMARTWORKPLACE
  IDENTIFIED BY smartworkplace
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT RESOURCE TO SMARTWORKPLACE;
  GRANT CONNECT TO SMARTWORKPLACE;
  ALTER USER SMARTWORKPLACE DEFAULT ROLE ALL; 
  GRANT UNLIMITED TABLESPACE TO SMARTWORKPLACE;