--------------------------------------------------------
--  File created - Tuesday-May-27-2014   
--------------------------------------------------------
REM INSERTING into SMARTWORKPLACE.DESKS
SET DEFINE OFF;
Insert into SMARTWORKPLACE.DESKS (ROOM_ID,DESK_NUMBER,DESK_DIMENSIONS) values (101,1,'150,150 150,160 160,160 160,150');
REM INSERTING into SMARTWORKPLACE.DEVICES
SET DEFINE OFF;
Insert into SMARTWORKPLACE.DEVICES (DEVICE_ID,DEVICE_NAME,DEVICE_TYPE,EMPLOYEE_ID) values ('14.311.313','DELL Precision M4700','Laptop',101);
REM INSERTING into SMARTWORKPLACE.EMPLOYEES
SET DEFINE OFF;
Insert into SMARTWORKPLACE.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,MIDDLE_NAME,LAST_NAME,JOB_TITLE,EXPERTISE) values (101,'Robert','van','Molken','Senior Integration Specialist','SOA Suite, OSB, BAM, OEP, XML, SOAP, HTML, PHP, MySQL');
REM INSERTING into SMARTWORKPLACE.OCCUPANCIES
SET DEFINE OFF;
REM INSERTING into SMARTWORKPLACE.ROOMS
SET DEFINE OFF;
Insert into SMARTWORKPLACE.ROOMS (ROOM_ID,ROOM_NAME,ROOM_DIMENSIONS,DOOR_LOCATION) values (202,'2.02','100,100 100,150 200,150 200,100','150,120 150,150');
