prompt >> Drop sequences
DROP SEQUENCE employees_seq;

prompt >> Drop tables
DROP TABLE occupancies CASCADE CONSTRAINTS;
DROP TABLE desks CASCADE CONSTRAINTS;
DROP TABLE rooms CASCADE CONSTRAINTS;
DROP TABLE devices CASCADE CONSTRAINTS;
DROP TABLE employees CASCADE CONSTRAINTS;