prompt >> Creation of table OCCUPANCIES
create table OCCUPANCIES
(
  CARD_ID       number              not null,
  DEVICE_ID     varchar2(50 char)   not null,
  ROOM_ID       number              not null,
  DESK_NUMBER   number              not null
)
/

ALTER TABLE OCCUPANCIES 
ADD CONSTRAINT OCCU_PK PRIMARY KEY ( CARD_ID ) ;
	
ALTER TABLE OCCUPANCIES
ADD CONSTRAINT OCCU_ROOM_FK
    FOREIGN KEY (ROOM_ID)
    REFERENCES ROOMS (ROOM_ID);
	
ALTER TABLE OCCUPANCIES
ADD CONSTRAINT OCCU_DEVI_FK
    FOREIGN KEY (DEVICE_ID)
    REFERENCES DEVICES (DEVICE_ID);
	
ALTER TABLE OCCUPANCIES
ADD CONSTRAINT OCCU_DESK_FK
    FOREIGN KEY (ROOM_ID, DESK_NUMBER)
    REFERENCES DESKS (ROOM_ID, DESK_NUMBER);
		
CREATE INDEX OCCU_ROOM_FK_I
    ON OCCUPANCIES (ROOM_ID);
	
CREATE INDEX OCCU_DEVI_FK_I
    ON OCCUPANCIES (DEVICE_ID);